def generate_recipe(audit_log: list, original_filename: str) -> str:
    """
    Generate a runnable Python script from the audit log that reproduces
    every cleaning step using pandas.
    """
    lines = [
        "import pandas as pd",
        "import numpy as np",
        "",
        f"# Reproducibility recipe generated by CleanSlate",
        f"# Original file: {original_filename}",
        "",
        f"df = pd.read_csv('{original_filename}')",
        "",
    ]

    # Methods that don't change data — emit as comments
    no_op_methods = {
        'type_confirmation', 'zero_kept_valid', 'skip_column',
        'keep_duplicates', 'type_conversion_skipped',
    }

    for entry in audit_log:
        method = entry['method']
        col = entry['column']
        details = entry.get('details', {})

        lines.append(f"# {entry.get('decision', method)} — {col}")

        if method in no_op_methods:
            lines.append(f"# (No data change)")
            lines.append("")
            continue

        if method == 'replace_disguised_nulls':
            values = details.get('values_replaced', [])
            lines.append(f"df['{col}'] = df['{col}'].replace({values}, np.nan)")

        elif method == 'zero_as_missing':
            lines.append(f"df.loc[df['{col}'] == 0, '{col}'] = np.nan")

        elif method == 'drop_empty_column':
            lines.append(f"df = df.drop(columns=['{col}'])")

        elif method == 'drop_rows_high_missingness':
            threshold = details.get('threshold', 0.3)
            lines.append(f"row_missing_pct = df.isna().sum(axis=1) / len(df.columns)")
            lines.append(f"df = df[row_missing_pct < {threshold}].reset_index(drop=True)")

        elif method == 'drop_rows_column_missing':
            lines.append(f"df = df.dropna(subset=['{col}']).reset_index(drop=True)")

        elif method == 'impute_mean':
            val = details.get('value')
            lines.append(f"df['{col}'] = df['{col}'].fillna({val})")

        elif method == 'impute_median':
            val = details.get('value')
            lines.append(f"df['{col}'] = df['{col}'].fillna({val})")

        elif method == 'impute_mode':
            val = details.get('value')
            lines.append(f"df['{col}'] = df['{col}'].fillna('{val}')")

        elif method == 'impute_group_median':
            group_cols = details.get('group_by', [])
            global_med = details.get('global_median')
            group_str = str(group_cols)
            lines.append(f"_group_med = df.groupby({group_str})['{col}'].transform('median')")
            lines.append(f"df['{col}'] = df['{col}'].fillna(_group_med)")
            lines.append(f"df['{col}'] = df['{col}'].fillna({global_med})  # fallback")

        elif method == 'impute_group_median_fallback':
            global_med = details.get('global_median')
            lines.append(f"df['{col}'] = df['{col}'].fillna({global_med})")

        elif method == 'impute_custom_value':
            val = details.get('value')
            if isinstance(val, str):
                lines.append(f"df['{col}'] = df['{col}'].fillna('{val}')")
            else:
                lines.append(f"df['{col}'] = df['{col}'].fillna({val})")

        elif method == 'impute_marker_unknown':
            marker = details.get('marker', 'Unknown')
            lines.append(f"df['{col}'] = df['{col}'].fillna('{marker}')")

        elif method in ('impute_most_recent_date', 'impute_oldest_date', 'impute_median_date'):
            fill_val = details.get('fill_value', '')
            lines.append(f"df['{col}'] = df['{col}'].fillna(pd.Timestamp('{fill_val}'))")

        elif method == 'type_conversion':
            target = details.get('target_type', '')
            if target == 'Continuous Number':
                lines.append(f"df['{col}'] = pd.to_numeric(df['{col}'], errors='coerce')")
            elif target == 'Date / Time':
                lines.append(f"df['{col}'] = pd.to_datetime(df['{col}'], errors='coerce')")
            elif target == 'Category':
                lines.append(f"df['{col}'] = df['{col}'].astype('category')")
            elif target == 'Boolean':
                lines.append(f"df['{col}'] = df['{col}'].map({{'true': True, 'false': False, 'yes': True, 'no': False, '1': True, '0': False}}).astype(bool)")
            elif target in ('Text', 'ID / Identifier'):
                lines.append(f"df['{col}'] = df['{col}'].astype(str)")

        elif method == 'remove_duplicates_keep_first':
            lines.append(f"df = df.drop_duplicates(keep='first').reset_index(drop=True)")

        elif method == 'remove_duplicates_keep_last':
            lines.append(f"df = df.drop_duplicates(keep='last').reset_index(drop=True)")

        else:
            lines.append(f"# Unknown method: {method}")

        lines.append("")

    lines.append(f"# Save cleaned data")
    lines.append(f"df.to_csv('clean_{original_filename}', index=False)")
    lines.append("")

    return "\n".join(lines)
